# Generated by Django 5.0.6 on 2024-08-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("first_cluster_label", models.IntegerField(blank=True, null=True)),
                ("second_cluster_label", models.IntegerField(blank=True, null=True)),
                ("user_input", models.TextField(blank=True, null=True)),
                ("symptoms", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
