# Generated by Django 5.0.6 on 2024-08-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinteraction",
            name="symptoms",
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="first_symptom",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="second_symptom_1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="second_symptom_2",
            field=models.TextField(blank=True, null=True),
        ),
    ]
