# Generated by Django 5.0.6 on 2024-08-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_app", "0002_remove_userinteraction_symptoms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinteraction",
            name="user_status",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
